version: "3.6"

services:
  # PHP + Apache server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/apache:/etc/apache2/sites-enabled
    ports:
      - 80:80
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - fyoussef

  # Mariadb server
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=ddd
    networks:
      - fyoussef

networks:
  fyoussef:
    driver: bridge
