FROM php:8.1-apache

# php extensions
RUN docker-php-ext-install pdo_mysql

# PHP composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install